@BattleShip.API_HostAddress = http://localhost:5186

POST {{BattleShip.API_HostAddress}}/newGame
Accept: application/json
Content-Type: application/json

POST {{BattleShip.API_HostAddress}}/attack/{{gameId}}?x={{x}}&y={{y}}
Accept: application/json
Content-Type: application/json